[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/app"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Dmitry Belyaev <mail@d-belyaev.ru>"]
license = "BSD-3-Clause"
publish = false

[workspace.dependencies]
anyhow = "1.0.103"
parking_lot = "0.12.5"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_yaml = "0.9.33"
tauri = { version = "2.11.5", features = ["tracing", "config-toml"] }
tauri-build = "2.6.3"
test-case = "3.3.1"
thiserror = "2.0.18"

[workspace.lints]
clippy.correctness = { priority = -1, level = "deny" }
clippy.suspicious = { priority = -1, level = "deny" }
clippy.complexity = { priority = -1, level = "deny" }
clippy.perf = { priority = -1, level = "deny" }
clippy.style = { priority = -1, level = "warn" }
clippy.pedantic = { priority = -1, level = "warn" }
clippy.cargo = { priority = -1, level = "warn" }
clippy.nursery = { priority = -1, level = "warn" }
clippy.multiple-crate-versions = "allow"
clippy.use_self = "allow"
clippy.missing_errors_doc = "allow"
